# Generated by Django 3.2.15 on 2022-08-22 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p1app', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
